import "./globals.css";
import { Globalcontext } from "./GlobalContext";
export const metadata = {
  title: "Blog app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body>
          <Globalcontext>{children}</Globalcontext>
        </body>
      </html>
    </>
  );
}
